version: '2'
services:
  producer:
    build: producer
    volumes:
     - ./producer:/app
    depends_on:
     - redis
  web:
    build: ui
    volumes:
     - ./ui:/app
    ports:
      - "3000:3000"
    depends_on:
     - redis
  redis:
    image: redis